### ISSUE TITLE
The transaction_identifier hash field value is equal to block_identifier hash value

### ISSUE THREAD

**Issue by UMANGAWASTHY** [ava-labs/avalanche-rosetta#36]
Hello Team,

**The transaction_identifier hash field value is equal to block_identifier hash value on Import operation Type. Any region why it is?**

Rosetta Query input -:
{
    "network_identifier":  {
        "blockchain": "Avalanche",
        "network": "Mainnet"
    },
    "block_identifier": {
        "index":3010277
    }
}
Url : http://127.0.0.1:9650/block

Output:
![image](https://user-images.githubusercontent.com/29591202/130742168-81d056a6-8904-44c5-8217-93f7a04ac80b.png)

**Comment by dhrubabasu** [comment]
This is because the initial release of avalanche-rosetta treated AtomicTxs as block transactions. There has been a TODO to fix this: 

https://github.com/ava-labs/avalanche-rosetta/blob/master/mapper/transaction.go#L250-L251

This PR will fix this issue https://github.com/ava-labs/avalanche-rosetta/pull/80

However, it requires integrators to re-index the chain so it's unclear on when this change will be merged in.
